/**
 * Liste des pays (libellés français) avec indicatif téléphonique.
 * Utilisée par le sélecteur de pays recherchable et le champ téléphone.
 */

export type Country = { code: string; name: string; dial: string };

export const COUNTRIES: Country[] = [
  { code: "ZA", name: "Afrique du Sud", dial: "+27" },
  { code: "DZ", name: "Algérie", dial: "+213" },
  { code: "DE", name: "Allemagne", dial: "+49" },
  { code: "SA", name: "Arabie saoudite", dial: "+966" },
  { code: "AR", name: "Argentine", dial: "+54" },
  { code: "AU", name: "Australie", dial: "+61" },
  { code: "AT", name: "Autriche", dial: "+43" },
  { code: "BH", name: "Bahreïn", dial: "+973" },
  { code: "BD", name: "Bangladesh", dial: "+880" },
  { code: "BE", name: "Belgique", dial: "+32" },
  { code: "BO", name: "Bolivie", dial: "+591" },
  { code: "BR", name: "Brésil", dial: "+55" },
  { code: "BG", name: "Bulgarie", dial: "+359" },
  { code: "BF", name: "Burkina Faso", dial: "+226" },
  { code: "CM", name: "Cameroun", dial: "+237" },
  { code: "CA", name: "Canada", dial: "+1" },
  { code: "CL", name: "Chili", dial: "+56" },
  { code: "CN", name: "Chine", dial: "+86" },
  { code: "CO", name: "Colombie", dial: "+57" },
  { code: "CG", name: "Congo-Brazzaville", dial: "+242" },
  { code: "CD", name: "Congo-Kinshasa", dial: "+243" },
  { code: "KR", name: "Corée du Sud", dial: "+82" },
  { code: "CR", name: "Costa Rica", dial: "+506" },
  { code: "CI", name: "Côte d’Ivoire", dial: "+225" },
  { code: "HR", name: "Croatie", dial: "+385" },
  { code: "CU", name: "Cuba", dial: "+53" },
  { code: "DK", name: "Danemark", dial: "+45" },
  { code: "EG", name: "Égypte", dial: "+20" },
  { code: "AE", name: "Émirats arabes unis", dial: "+971" },
  { code: "EC", name: "Équateur", dial: "+593" },
  { code: "ES", name: "Espagne", dial: "+34" },
  { code: "US", name: "États-Unis", dial: "+1" },
  { code: "ET", name: "Éthiopie", dial: "+251" },
  { code: "FI", name: "Finlande", dial: "+358" },
  { code: "FR", name: "France", dial: "+33" },
  { code: "GA", name: "Gabon", dial: "+241" },
  { code: "GH", name: "Ghana", dial: "+233" },
  { code: "GR", name: "Grèce", dial: "+30" },
  { code: "GT", name: "Guatemala", dial: "+502" },
  { code: "HT", name: "Haïti", dial: "+509" },
  { code: "HN", name: "Honduras", dial: "+504" },
  { code: "HU", name: "Hongrie", dial: "+36" },
  { code: "IN", name: "Inde", dial: "+91" },
  { code: "ID", name: "Indonésie", dial: "+62" },
  { code: "IQ", name: "Irak", dial: "+964" },
  { code: "IR", name: "Iran", dial: "+98" },
  { code: "IE", name: "Irlande", dial: "+353" },
  { code: "IL", name: "Israël", dial: "+972" },
  { code: "IT", name: "Italie", dial: "+39" },
  { code: "JM", name: "Jamaïque", dial: "+1" },
  { code: "JP", name: "Japon", dial: "+81" },
  { code: "JO", name: "Jordanie", dial: "+962" },
  { code: "KE", name: "Kenya", dial: "+254" },
  { code: "KW", name: "Koweït", dial: "+965" },
  { code: "LB", name: "Liban", dial: "+961" },
  { code: "LY", name: "Libye", dial: "+218" },
  { code: "LU", name: "Luxembourg", dial: "+352" },
  { code: "MY", name: "Malaisie", dial: "+60" },
  { code: "ML", name: "Mali", dial: "+223" },
  { code: "MA", name: "Maroc", dial: "+212" },
  { code: "MR", name: "Mauritanie", dial: "+222" },
  { code: "MX", name: "Mexique", dial: "+52" },
  { code: "MC", name: "Monaco", dial: "+377" },
  { code: "NI", name: "Nicaragua", dial: "+505" },
  { code: "NE", name: "Niger", dial: "+227" },
  { code: "NG", name: "Nigeria", dial: "+234" },
  { code: "NO", name: "Norvège", dial: "+47" },
  { code: "NZ", name: "Nouvelle-Zélande", dial: "+64" },
  { code: "OM", name: "Oman", dial: "+968" },
  { code: "UG", name: "Ouganda", dial: "+256" },
  { code: "PK", name: "Pakistan", dial: "+92" },
  { code: "PA", name: "Panama", dial: "+507" },
  { code: "PY", name: "Paraguay", dial: "+595" },
  { code: "NL", name: "Pays-Bas", dial: "+31" },
  { code: "PE", name: "Pérou", dial: "+51" },
  { code: "PH", name: "Philippines", dial: "+63" },
  { code: "PL", name: "Pologne", dial: "+48" },
  { code: "PT", name: "Portugal", dial: "+351" },
  { code: "QA", name: "Qatar", dial: "+974" },
  { code: "HK", name: "R.A.S. chinoise de Hong Kong", dial: "+852" },
  { code: "DO", name: "République dominicaine", dial: "+1" },
  { code: "RO", name: "Roumanie", dial: "+40" },
  { code: "GB", name: "Royaume-Uni", dial: "+44" },
  { code: "RU", name: "Russie", dial: "+7" },
  { code: "RW", name: "Rwanda", dial: "+250" },
  { code: "SV", name: "Salvador", dial: "+503" },
  { code: "SN", name: "Sénégal", dial: "+221" },
  { code: "RS", name: "Serbie", dial: "+381" },
  { code: "SG", name: "Singapour", dial: "+65" },
  { code: "SD", name: "Soudan", dial: "+249" },
  { code: "LK", name: "Sri Lanka", dial: "+94" },
  { code: "SE", name: "Suède", dial: "+46" },
  { code: "CH", name: "Suisse", dial: "+41" },
  { code: "SY", name: "Syrie", dial: "+963" },
  { code: "TW", name: "Taïwan", dial: "+886" },
  { code: "TZ", name: "Tanzanie", dial: "+255" },
  { code: "TD", name: "Tchad", dial: "+235" },
  { code: "CZ", name: "Tchéquie", dial: "+420" },
  { code: "PS", name: "Territoires palestiniens", dial: "+970" },
  { code: "TH", name: "Thaïlande", dial: "+66" },
  { code: "TT", name: "Trinité-et-Tobago", dial: "+1" },
  { code: "TN", name: "Tunisie", dial: "+216" },
  { code: "TR", name: "Turquie", dial: "+90" },
  { code: "UA", name: "Ukraine", dial: "+380" },
  { code: "UY", name: "Uruguay", dial: "+598" },
  { code: "VE", name: "Venezuela", dial: "+58" },
  { code: "VN", name: "Viêt Nam", dial: "+84" },
];

/** Recherche insensible à la casse et aux accents (« tun » trouve « Tunisie »). */
export function searchCountries(query: string): Country[] {
  const q = query.trim().normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
  if (!q) return COUNTRIES;
  return COUNTRIES.filter((c) => {
    const name = c.name.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
    return name.includes(q) || c.dial.includes(q) || c.code.toLowerCase() === q;
  });
}

export const countryByCode = (code: string | null | undefined): Country | null =>
  code ? (COUNTRIES.find((c) => c.code === code) ?? null) : null;
